"""empty message

Revision ID: 1391a7683bfe
Revises: 3b3b920aee41
Create Date: 2024-06-15 21:51:33.498685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1391a7683bfe'
down_revision = '3b3b920aee41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('cover_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'cover', ['cover_id'], ['id'])

    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.drop_constraint('cover_ibfk_1', type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cover_ibfk_1', 'book', ['book_id'], ['id'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cover_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
