"""empty message

Revision ID: 1fdb1a2d356e
Revises: 1391a7683bfe
Create Date: 2024-06-15 21:52:23.980082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fdb1a2d356e'
down_revision = '1391a7683bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cover_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_id', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
