"""empty message

Revision ID: 347d78ffec37
Revises: 1fdb1a2d356e
Create Date: 2024-06-15 23:26:50.092970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '347d78ffec37'
down_revision = '1fdb1a2d356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('short_desc',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('short_desc',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
