"""empty message

Revision ID: 355ba6ee7f9d
Revises: c9293ce12f78
Create Date: 2024-06-14 16:02:42.488474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355ba6ee7f9d'
down_revision = 'c9293ce12f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
