"""empty message

Revision ID: 7060385bac8e
Revises: f8780d1d97e5
Create Date: 2024-06-13 21:15:52.344874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7060385bac8e'
down_revision = 'f8780d1d97e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('rating_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('rating_count')

    # ### end Alembic commands ###
