"""empty message

Revision ID: 920d4da0532c
Revises: 294b7aba4ef5
Create Date: 2024-06-13 17:10:50.678405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920d4da0532c'
down_revision = '294b7aba4ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_to_book_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('category_to_book_id')

    # ### end Alembic commands ###
