"""empty message

Revision ID: 995b547262ad
Revises: 81119c21e48a
Create Date: 2024-06-13 20:52:07.925164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '995b547262ad'
down_revision = '81119c21e48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('book_ibfk_1', type_='foreignkey')
        batch_op.drop_column('cover_id')

    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('book_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_foreign_key('book_ibfk_1', 'cover', ['cover_id'], ['id'])

    # ### end Alembic commands ###
