"""empty message

Revision ID: dbdac7ff7a76
Revises: c743d7e18b0a
Create Date: 2024-06-13 19:57:40.091849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbdac7ff7a76'
down_revision = 'c743d7e18b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cover', ['cover_id'], ['id'])

    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.drop_constraint('cover_ibfk_1', type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cover_ibfk_1', 'book', ['book_id'], ['id'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_id')

    # ### end Alembic commands ###
