"""empty message

Revision ID: ecd9c584ff60
Revises: f04054a7f510
Create Date: 2024-06-13 20:23:03.974803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd9c584ff60'
down_revision = 'f04054a7f510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'role', ['cover_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_id')

    # ### end Alembic commands ###
